// Code generated by MockGen. DO NOT EDIT.
// Source: conductor/pets_conductor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	"github.com/aws/aws-sdk-go/service/sqs"
	"github.com/aws/aws-sdk-go/service/sqs/sqsiface"
	//	gomock "github.com/golang/mock/gomock"
)

type MockedReceiveMsgs struct {
	sqsiface.SQSAPI
	Resp sqs.ReceiveMessageOutput
}
