// Code generated by MockGen. DO NOT EDIT.
// Source: conductor/supplies_conductor.go

// Package mocks is a generated GoMock package.
package mocks

import (
//gomock "github.com/golang/mock/gomock"
)
